### ISSUE TITLE
Theme Default spanish language - New folders are not links

### ISSUE THREAD

**Issue by joniuz** [jimjag/telaen#3]
Hi!

I updated to Telaen 1.3.2 and i found some issues.

The folders created by users are not links in the left menu. 

I am using the Theme default with spanish language and PHP 5.3.3. 

I attached a image.

Regards
Jose Zorrilla

![telaennewfolders](https://cloud.githubusercontent.com/assets/12822475/8079101/c311fab2-0fa5-11e5-984a-b1bef7e7df24.png)

**Comment by jimjag** [comment]
Thx. Are you using IMAP or POP3?

**Comment by joniuz** [comment]
We are using POP3 but actually we solved the problem, there is a open html tag in the template menu
