### ISSUE TITLE
Unable to deploy telaen on Centos 7

### ISSUE THREAD

**Issue by vlnrajesh** [jimjag/telaen#4]
Hi,

I am getting below error while pushing the telaen
PHP Fatal error:  require_once(): Failed opening required '/var/chef/cache/smarty_move_meSmarty.class.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/webmail/index.php on line 17
Attaching screen shot of test execution, which says all passed.

Please guide me.

![screen shot 2015-07-28 at 7 54 11 pm](https://cloud.githubusercontent.com/assets/7330957/8933842/7533fbfa-3562-11e5-8fe0-7c0e81018be8.png)

**Comment by vlnrajesh** [comment]
Any help is appreciated.

**Comment by joniuz** [comment]
Hi,

First check that you have the last "/" character in the configuration for the variable SMARTY_DIR

Check the configuration file inc/config/config.php,  in my installation the SMARTY_DIR line is:

define("SMARTY_DIR","/var/www/telaen_1.3.2/smarty/");

Probably the check installation script only verify the folder but not the contents of the folder and if this content is readable by the web server user.

And those are the contents in my folder. All can be read by everyone and specifically by the web user

[root@mx /]# ls -la /var/www/telaen_1.3.2/smarty/
total 232
drwxr-xr-x 4 root root  4096 jun  8 22:34 .
drwxr-xr-x 3 root root  4096 jun  8 22:34 ..
-rw-r--r-- 1 root root 12918 jun  8 22:34 Config_File.class.php
-rw-r--r-- 1 root root 24389 jun  8 22:34 COPYING.lib
-rw-r--r-- 1 root root    13 jun  8 22:34 .cvsignore
-rw-r--r-- 1 root root  3562 jun  8 22:34 debug.tpl
drwxr-xr-x 2 root root  4096 jun  8 22:34 internals
drwxr-xr-x 2 root root  4096 jun  8 22:34 plugins
-rw-r--r-- 1 root root 63629 jun  8 22:34 Smarty.class.php
-rw-r--r-- 1 root root 94367 jun  8 22:34 Smarty_Compiler.class.php
[root@mx /]#

Good luck!

**Comment by jimjag** [comment]
Yes, the error message '/var/chef/cache/smarty_move_meSmarty.class.php' implies that the SMARTY_DIR var isn't set and lacks the '/' deliminator (It should be, e.g., '/var/chef/cache/smarty_move_me/Smarty.class.php', note the '/' between the smarty_move_me and Smarty.php
