### ISSUE TITLE
SQLite3 class not found

### ISSUE THREAD

**Issue by jazzmang** [jimjag/telaen#7]
I keep running into this error any time I try the new v2.0 from the master branch ast of this post:

Class 'Telaen\\LocalMbox\\SQLite3' not found in xxxxxxxx/inc/class/class.LocalMbox.php on line 17,

SQLite3 is installed and test fine with the check_install.php.

**Comment by jimjag** [comment]
Thx for the report. I just closed this issue with a patch. Please re-open if this does not fix it for you.

**Comment by jazzmang** [comment]
Well that solved that issue but created a similar in a different file:

Class 'Telaen' not found in xxxxx/inc/preinit.php on line 32
