### ISSUE TITLE
Class 'Telaen' not found in xxxxx/inc/preinit.php on line 32

### ISSUE THREAD

**Issue by jazzmang** [jimjag/telaen#8]
Not sure if this is another case similar to the SQLite3 class not found &  needing a "use" added but...

Here is what I did: After the SQLite3 update, I found that inc/class/class.Telaen.php on line 9 was trying to call ./inc/vendor/class.TNEF.php when it is in the same inc/class/ folder. So I change that path.

But then it lead me to this error:

PHP Fatal error:  Uncaught Error: Class 'Telaen' not found in xxxx/inc/preinit.php:32\nStack trace:\n#0 xxxx/index.php(11): require_once()\n#1 {main}\n  thrown in xxxx/inc/preinit.php on line 32

**Comment by jimjag** [comment]
Yeah... trunk/master is a work in progress and will likely have issues like this. Thanks for helping me catch these on different systems. Let me dig into it.
